################################################################
# Basys3 Slide Switch to LED Project Creation Script
# Project: basys3_switch_led
# Description: Connect 16 slide switches to 16 LEDs
# Board: Digilent Basys3 (Artix-7 XC7A35T)
################################################################

# Set project variables
set project_name "basys3_switch_led"
set project_dir "C:/Users/Administrator/${project_name}"
set top_module "switch_led_top"
set part_name "xc7a35tcpg236-1"
set board_part "digilentinc.com:basys3:part0:1.1"

# Create project directory
file mkdir $project_dir

puts "================================================================"
puts "Creating Basys3 Switch-LED Project"
puts "================================================================"

# Create project
puts "INFO: Creating project ${project_name}..."
create_project $project_name $project_dir -part $part_name -force

# Set board part if available
if {[catch {set_property board_part $board_part [current_project]} err]} {
    puts "WARNING: Board part not found, using part only"
} else {
    puts "INFO: Board part set to ${board_part}"
}

# Set project properties
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

puts "INFO: Project created successfully"

################################################################
# Create Verilog Source File
################################################################
puts "INFO: Creating Verilog source file..."

set verilog_file "${project_dir}/${top_module}.v"
set verilog_content {`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: Auto-generated by TCL Script
// 
// Create Date: [clock format [clock seconds]]
// Design Name: Switch to LED
// Module Name: switch_led_top
// Project Name: basys3_switch_led
// Target Devices: Basys3 (Artix-7)
// Tool Versions: Vivado 2022.2
// Description: Connect 16 slide switches directly to 16 LEDs
// 
// Dependencies: None
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
//   - SW[15:0] -> LED[15:0]
//   - No clock required (combinational logic only)
//////////////////////////////////////////////////////////////////////////////////

module switch_led_top(
    input  wire [15:0] sw,      // 16 slide switches
    output wire [15:0] led      // 16 LEDs
    );
    
    // Direct connection: switches control LEDs
    assign led = sw;
    
endmodule
}

set fp [open $verilog_file w]
puts $fp $verilog_content
close $fp

# Add source file to project
add_files -norecurse $verilog_file
set_property top $top_module [current_fileset]
update_compile_order -fileset sources_1

puts "INFO: Verilog source file created: ${verilog_file}"

################################################################
# Create XDC Constraint File
################################################################
puts "INFO: Creating XDC constraint file..."

set xdc_file "${project_dir}/basys3_constraints.xdc"
set xdc_content {## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used ports
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

################################################################
# Clock Signal (not used in this project, but included for reference)
################################################################
#set_property PACKAGE_PIN W5 [get_ports clk]
#    set_property IOSTANDARD LVCMOS33 [get_ports clk]
#    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

################################################################
# Switches
################################################################
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

################################################################
# LEDs
################################################################
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

################################################################
# Configuration Options
################################################################
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
}

set fp [open $xdc_file w]
puts $fp $xdc_content
close $fp

# Add constraint file to project
add_files -fileset constrs_1 -norecurse $xdc_file

puts "INFO: XDC constraint file created: ${xdc_file}"

################################################################
# Run Synthesis
################################################################
puts ""
puts "================================================================"
puts "Starting Synthesis"
puts "================================================================"

# Reset and launch synthesis
reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1

# Check synthesis result
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    error "ERROR: Synthesis failed!"
}
puts "INFO: ✓ Synthesis completed successfully"

################################################################
# Run Implementation
################################################################
puts ""
puts "================================================================"
puts "Starting Implementation"
puts "================================================================"

launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Check implementation result
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    error "ERROR: Implementation failed!"
}
puts "INFO: ✓ Implementation completed successfully"

################################################################
# Generate Reports
################################################################
puts ""
puts "================================================================"
puts "Generating Reports"
puts "================================================================"

set report_dir "${project_dir}/reports"
file mkdir $report_dir

# Open implemented design
open_run impl_1

# Generate utilization report
puts "INFO: Generating utilization report..."
report_utilization -file ${report_dir}/utilization.txt
report_utilization -hierarchical -file ${report_dir}/utilization_hierarchical.txt

# Generate timing report (no timing constraints in this design)
puts "INFO: Generating timing report..."
report_timing_summary -file ${report_dir}/timing_summary.txt

# Generate power report
puts "INFO: Generating power report..."
report_power -file ${report_dir}/power.txt

# Generate DRC report
puts "INFO: Generating DRC report..."
report_drc -file ${report_dir}/drc.txt

# Generate IO report
puts "INFO: Generating IO report..."
report_io -file ${report_dir}/io.txt

puts "INFO: ✓ All reports generated"

################################################################
# Copy Output Files
################################################################
puts ""
puts "================================================================"
puts "Organizing Output Files"
puts "================================================================"

set output_dir "${project_dir}/output_files"
file mkdir $output_dir

# Copy bitstream
set bit_src "${project_dir}/${project_name}.runs/impl_1/${top_module}.bit"
set bit_dst "${output_dir}/${top_module}.bit"
if {[file exists $bit_src]} {
    file copy -force $bit_src $bit_dst
    puts "INFO: ✓ Bitstream copied to: ${bit_dst}"
} else {
    puts "ERROR: Bitstream file not found!"
}

# Copy bin file (for programming)
set bin_src "${project_dir}/${project_name}.runs/impl_1/${top_module}.bin"
set bin_dst "${output_dir}/${top_module}.bin"
if {[file exists $bin_src]} {
    file copy -force $bin_src $bin_dst
    puts "INFO: ✓ Binary file copied to: ${bin_dst}"
}

# Copy source files
file copy -force $verilog_file ${output_dir}/
file copy -force $xdc_file ${output_dir}/
puts "INFO: ✓ Source files copied"

################################################################
# Create README
################################################################
set readme_file "${output_dir}/README.txt"
set readme_content "================================================================
Basys3 Switch-LED Project
================================================================
Generated: [clock format [clock seconds] -format "%Y-%m-%d %H:%M:%S"]

================================================================
PROJECT INFORMATION
================================================================
Project Name:  ${project_name}
Top Module:    ${top_module}
Board:         Digilent Basys3
FPGA Part:     ${part_name}

================================================================
DESIGN DESCRIPTION
================================================================
This is a simple combinational logic design that connects:
  - 16 Slide Switches (SW0-SW15) → 16 LEDs (LD0-LD15)

Behavior:
  - When a switch is UP (ON), corresponding LED lights up
  - When a switch is DOWN (OFF), corresponding LED turns off
  - No clock required (purely combinational)

================================================================
FILES INCLUDED
================================================================
1. ${top_module}.bit
   - FPGA bitstream file for programming

2. ${top_module}.bin  
   - Binary format (alternative programming format)

3. ${top_module}.v
   - Verilog source code

4. basys3_constraints.xdc
   - Pin constraints (switch and LED mappings)

================================================================
HARDWARE SETUP
================================================================
Basys3 Board Layout:
  - SW0-SW15: Located at bottom of board (16 slide switches)
  - LD0-LD15: Located at top of board (16 green LEDs)

Switch Positions:
  SW0  = Rightmost switch
  SW15 = Leftmost switch

LED Positions:
  LD0  = Rightmost LED
  LD15 = Leftmost LED

================================================================
PROGRAMMING THE FPGA
================================================================
Method 1: Using Vivado Hardware Manager
1. Connect Basys3 to PC via USB
2. Power on the board (slide power switch to ON)
3. Open Vivado Hardware Manager
4. Click 'Auto Connect'
5. Right-click on device → 'Program Device'
6. Select: ${top_module}.bit
7. Click 'Program'

Method 2: Using Vivado TCL Console
open_hw_manager
connect_hw_server
open_hw_target
set_property PROGRAM.FILE {${bit_dst}} [get_hw_devices xc7a35t_0]
program_hw_devices [get_hw_devices xc7a35t_0]
refresh_hw_device [get_hw_devices xc7a35t_0]

Method 3: Command Line (Windows)
cd C:/Xilinx/Vivado/2022.2/bin
vivado -mode batch -source program_basys3.tcl

================================================================
TESTING THE DESIGN
================================================================
After programming:
1. Flip any slide switch UP → corresponding LED should light
2. Flip switch DOWN → LED should turn off
3. Try different switch combinations
4. All 16 switches control their respective LEDs independently

Example Tests:
  - SW0 UP    → LD0 ON
  - SW15 UP   → LD15 ON
  - All UP    → All LEDs ON
  - All DOWN  → All LEDs OFF
  - Pattern: 10101010 → Alternating LEDs

================================================================
RESOURCE UTILIZATION
================================================================
This design uses minimal FPGA resources:
  - LUTs: 0 (direct wire connections)
  - FFs:  0 (no sequential logic)
  - IOs:  32 (16 inputs + 16 outputs)

================================================================
TROUBLESHOOTING
================================================================
Issue: LEDs don't light up
  → Check board power is ON
  → Verify bitstream was programmed successfully
  → Check USB cable connection

Issue: Some LEDs always on/off
  → Reprogram the bitstream
  → Check for loose connections

Issue: Programming fails
  → Install Digilent Board Files
  → Update Vivado cable drivers
  → Try different USB port

================================================================
REFERENCES
================================================================
- Basys3 Reference Manual: 
  https://digilent.com/reference/programmable-logic/basys-3/
  
- Basys3 Master XDC File:
  https://github.com/Digilent/digilent-xdc/

- Vivado Design Suite User Guide:
  UG893, UG894, UG895

================================================================
"

set fp [open $readme_file w]
puts $fp $readme_content
close $fp
puts "INFO: ✓ README created"

################################################################
# Create Programming Script
################################################################
set prog_tcl "${output_dir}/program_basys3.tcl"
set prog_content "# Basys3 Programming Script
# Auto-generated by project creation script

open_hw_manager
connect_hw_server -allow_non_jtag
open_hw_target

# Get Basys3 device
set device \[get_hw_devices xc7a35t_0\]

# Set bitstream file
set_property PROGRAM.FILE {${bit_dst}} \$device

# Program the device
puts \"Programming Basys3...\"
program_hw_devices \$device
refresh_hw_device \$device

puts \"Programming completed!\"
puts \"You can now test the switches and LEDs\"

# Keep hardware manager open
# close_hw_manager
"

set fp [open $prog_tcl w]
puts $fp $prog_content
close $fp
puts "INFO: ✓ Programming script created"

################################################################
# Create Project Summary
################################################################
set summary_file "${project_dir}/PROJECT_SUMMARY.txt"
set summary_content "================================================================
BASYS3 SWITCH-LED PROJECT SUMMARY
================================================================
Generated: [clock format [clock seconds] -format "%Y-%m-%d %H:%M:%S"]

================================================================
PROJECT DETAILS
================================================================
Name:        ${project_name}
Location:    ${project_dir}
Top Module:  ${top_module}
Board:       Digilent Basys3
Part:        ${part_name}

================================================================
DESIGN FILES
================================================================
Verilog Source:     ${verilog_file}
Constraint File:    ${xdc_file}
Top Module:         ${top_module}

Design Type:        Combinational Logic
Clock Required:     No
Sequential Logic:   No

================================================================
BUILD STATUS
================================================================
✓ Synthesis:       Completed
✓ Implementation:  Completed
✓ Bitstream:       Generated
✓ Reports:         Generated

================================================================
OUTPUT FILES
================================================================
📁 ${output_dir}/
   ├─ ${top_module}.bit              ⭐ Bitstream (for programming)
   ├─ ${top_module}.bin              💾 Binary format
   ├─ ${top_module}.v                📝 Verilog source
   ├─ basys3_constraints.xdc         📌 Constraints
   ├─ README.txt                     📖 Usage guide
   └─ program_basys3.tcl             🔧 Programming script

📁 ${report_dir}/
   ├─ utilization.txt                📊 Resource usage
   ├─ timing_summary.txt             ⏱️ Timing analysis
   ├─ power.txt                      🔋 Power analysis
   ├─ drc.txt                        ✅ Design checks
   └─ io.txt                         📍 IO assignment

================================================================
PIN ASSIGNMENTS
================================================================
Switches (Input):
  SW[0]  → V17    SW[8]  → V2
  SW[1]  → V16    SW[9]  → T3
  SW[2]  → W16    SW[10] → T2
  SW[3]  → W17    SW[11] → R3
  SW[4]  → W15    SW[12] → W2
  SW[5]  → V15    SW[13] → U1
  SW[6]  → W14    SW[14] → T1
  SW[7]  → W13    SW[15] → R2

LEDs (Output):
  LED[0]  → U16   LED[8]  → V13
  LED[1]  → E19   LED[9]  → V3
  LED[2]  → U19   LED[10] → W3
  LED[3]  → V19   LED[11] → U3
  LED[4]  → W18   LED[12] → P3
  LED[5]  → U15   LED[13] → N3
  LED[6]  → U14   LED[14] → P1
  LED[7]  → V14   LED[15] → L1

All signals use LVCMOS33 standard (3.3V)

================================================================
NEXT STEPS
================================================================
1. Program the FPGA:
   → Open: ${output_dir}/program_basys3.tcl
   → Or use Vivado Hardware Manager

2. Test the design:
   → Flip switches up/down
   → Watch corresponding LEDs

3. Modify if needed:
   → Edit: ${top_module}.v
   → Rebuild: source this script again

================================================================
"

set fp [open $summary_file w]
puts $fp $summary_content
close $fp

################################################################
# Final Output
################################################################
puts ""
puts "================================================================"
puts "🎉 PROJECT CREATION COMPLETED SUCCESSFULLY! 🎉"
puts "================================================================"
puts ""
puts "Project:  ${project_name}"
puts "Location: ${project_dir}"
puts ""
puts "Generated Files:"
puts "  ⚡ Bitstream:  ${output_dir}/${top_module}.bit"
puts "  📝 Verilog:   ${verilog_file}"
puts "  📌 XDC:       ${xdc_file}"
puts "  📊 Reports:   ${report_dir}/"
puts "  📖 Guide:     ${output_dir}/README.txt"
puts ""
puts "Design Summary:"
puts "  → 16 Switches connected to 16 LEDs"
puts "  → Combinational logic (no clock)"
puts "  → Ready to program!"
puts ""
puts "Next Steps:"
puts "  1. Connect Basys3 board via USB"
puts "  2. Run: source ${output_dir}/program_basys3.tcl"
puts "  3. Flip switches and watch LEDs!"
puts ""
puts "================================================================"
puts "For detailed instructions, see:"
puts "  ${output_dir}/README.txt"
puts "  ${summary_file}"
puts "================================================================"
